import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/navbar/Navbar'
import localFont from 'next/font/local';

const clash = localFont({
  src: [
    {
      path: './assets/fonts/clash/ClashDisplay-Extralight.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './assets/fonts/clash/ClashDisplay-Light.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/clash/ClashDisplay-Regular.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './assets/fonts/clash/ClashDisplay-Medium.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './assets/fonts/clash/ClashDisplay-Semibold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './assets/fonts/clash/ClashDisplay-Bold.otf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-Clashdisplay',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/montserrat"
          rel="stylesheet"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,1,300&display=swap" 
          rel="stylesheet">
        </link>
        {/*eslint-disable-next-line @next/next/no-page-custom-font*/}
        <link 
          href="https://fonts.googleapis.com/css2?family=Unica+One&display=swap" 
          rel="stylesheet"
          />
      </head>
      <body className={`${clash.variable}`}>
        <Navbar/>
        {children}
        
      </body>
    </html>
  )
}
